// This file is auto-generated by Convex.
// Run `npx convex dev` to generate the actual types.
// This is a stub to allow TypeScript compilation without a Convex deployment.

export const api = {} as any;
