// This file is auto-generated by Convex.
// Run `npx convex dev` to generate the actual types.
// This is a stub to allow TypeScript compilation without a Convex deployment.

export type GenericMutationCtx = any;
export type GenericQueryCtx = any;

export const query = (config: any) => config;
export const mutation = (config: any) => config;
export const action = (config: any) => config;
export const internalQuery = (config: any) => config;
export const internalMutation = (config: any) => config;
